apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
data:
  APP_NAME: {{ .Values.laravel.appName | quote }}
  APP_ENV: {{ .Values.laravel.appEnv | quote }}
  APP_DEBUG: {{ .Values.laravel.appDebug | quote }}
  APP_URL: {{ .Values.laravel.appUrl | quote }}
  
  DB_CONNECTION: {{ .Values.laravel.database.connection | quote }}
  DB_HOST: {{ .Values.laravel.database.host | quote }}
  DB_PORT: {{ .Values.laravel.database.port | quote }}
  DB_DATABASE: {{ .Values.laravel.database.database | quote }}
  
  CACHE_STORE: {{ .Values.laravel.cacheStore | quote }}
  SESSION_DRIVER: {{ .Values.laravel.sessionDriver | quote }}
  QUEUE_CONNECTION: {{ .Values.laravel.queueConnection | quote }}
  
  REDIS_CLIENT: "predis"
  REDIS_HOST: {{ .Values.laravel.redis.host | quote }}
  REDIS_PORT: {{ .Values.laravel.redis.port | quote }}