apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service.name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.laravel.database.username | quote }}
  DB_PASSWORD: {{ .Values.laravel.database.password | quote }}
  REDIS_PASSWORD: {{ .Values.laravel.redis.password | quote }}
  APP_KEY: "base64:CHANGE_THIS_IN_PRODUCTION"