apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-service-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
data:
  VITE_API_URL: {{ .Values.app.apiUrl | quote }}
  NODE_ENV: {{ .Values.app.nodeEnv | quote }}
  ENVIRONMENT: {{ .Values.environment | quote }}
  
  {{- if .Values.newrelic.enabled }}
  NEW_RELIC_ENABLED: "true"
  NEW_RELIC_APP_NAME: {{ .Values.newrelic.appName | quote }}
  NEW_RELIC_BROWSER_MONITORING_ENABLED: {{ .Values.newrelic.browserMonitoring | quote }}
  NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: "true"
  NEW_RELIC_LOG_LEVEL: "info"
  {{- else }}
  NEW_RELIC_ENABLED: "false"
  {{- end }}

---