{{- if .Values.newrelic.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: frontend-newrelic-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
    component: {{ .Values.labels.component }}
    environment: {{ .Values.labels.environment }}
type: Opaque
stringData:
  NEW_RELIC_LICENSE_KEY: {{ .Values.newrelic.licenseKey | quote }}
{{- end }}