{{- if .Values.newrelic.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: frontend-newrelic-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
type: Opaque
data:
  NEW_RELIC_LICENSE_KEY: {{ .Values.newrelic.licenseKey | b64enc | quote }}
{{- end }}

---