apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-dev
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/YOUR_USERNAME/resumebuilder-infrastructure.git
    targetRevision: develop
    path: helm/redis
    helm:
      valueFiles:
        - values.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: resumebuilder-dev
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true